import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, RefreshCw } from 'lucide-react'
import { api, type TaskGroup } from '@/api'

export function TaskGroupsPage() {
  const [groups, setGroups] = useState<TaskGroup[]>([]); const [error, setError] = useState(''); const [title, setTitle] = useState(''); const [taskType, setTaskType] = useState<TaskGroup['taskType']>('generic')
  const load = () => api.taskGroups().then(setGroups).catch(err => setError(err.message))
  useEffect(() => { void api.taskGroups().then(setGroups).catch(err => setError(err.message)) }, [])
  const create = async () => { try { const group = await api.createTaskGroup({ title, taskType }); setGroups(value => [...value, group]); setTitle('') } catch (err) { setError(err instanceof Error ? err.message : '创建失败') } }
  return <main className="aw-page"><section className="aw-page-header"><div className="aw-page-title-group"><h2>Task Groups</h2><span className="aw-counter-badge">confirmed comparable tasks</span></div><button className="aw-btn-view" type="button" onClick={load}><RefreshCw size={13} /> Refresh</button></section><section className="aw-task-create"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="任务组名称，例如：登录页修复" /><select value={taskType} onChange={event => setTaskType(event.target.value as TaskGroup['taskType'])}><option value="generic">Generic</option><option value="coding">Coding</option><option value="content">Content</option></select><button type="button" className="aw-btn-compare" disabled={!title.trim()} onClick={create}><Plus size={14} /> New task group</button></section>{error && <div className="aw-inline-error">{error}</div>}<section className="aw-task-list">{groups.map(group => <TaskGroupCard key={group.evalTaskId} group={group} />)}{!groups.length && <div className="aw-empty"><b>还没有任务组</b><p>从任意 Run 报告中确认同一个实际任务，才能进行控制变量比较。</p></div>}</section></main>
}

function TaskGroupCard({ group }: { group: TaskGroup }) {
  const [current, setCurrent] = useState(group); const [data, setData] = useState<any>(null); const [diagnostics, setDiagnostics] = useState<any>(null); const [error, setError] = useState('')
  const load = () => Promise.all([api.reliability(current.evalTaskId), api.taskDiagnostics(current.evalTaskId)]).then(([reliability, history]) => { setData(reliability); setDiagnostics(history) }).catch(err => setError(err.message))
  useEffect(() => { void Promise.all([api.reliability(current.evalTaskId), api.taskDiagnostics(current.evalTaskId)]).then(([reliability, history]) => { setData(reliability); setDiagnostics(history) }).catch(err => setError(err.message)) }, [current.evalTaskId])
  const setBaseline = async (index: number) => { try { setCurrent(await api.patchTaskGroup(current.evalTaskId, { baselineRun: current.confirmedRuns[index] })) } catch (err) { setError(err instanceof Error ? err.message : '更新 baseline 失败') } }
  const suggest = async () => { try { setCurrent(await api.refreshSuggestions(current.evalTaskId)) } catch (err) { setError(err instanceof Error ? err.message : '生成建议失败') } }
  const confirm = async (ref: TaskGroup['suggestedRuns'][number]) => { try { setCurrent(await api.addTaskRun(current.evalTaskId, ref)) } catch (err) { setError(err instanceof Error ? err.message : '确认失败') } }
  const baselineIndex = current.baselineRun ? current.confirmedRuns.findIndex(ref => ref.source === current.baselineRun?.source && ref.sessionId === current.baselineRun?.sessionId && ref.turnId === current.baselineRun?.turnId) : -1
  const compareLink = baselineIndex >= 0 ? `/compare?task=${current.evalTaskId}&baselineSession=${current.baselineRun!.sessionId}&baselineTurn=${current.baselineRun!.turnId}` : `/compare?task=${current.evalTaskId}`
  return <article className="aw-task-card"><header><div><span className="aw-eyebrow">{current.taskType}</span><h3>{current.title}</h3></div><Link className="aw-btn-view" to={compareLink}>Compare</Link></header><div className="aw-task-card-metrics"><span><b>{current.confirmedRuns.length}</b> confirmed runs</span><span><b>{current.baselineRun ? 'Set' : 'Missing'}</b> baseline</span><span><b>{data?.successRate == null ? 'Unavailable' : `${(data.successRate * 100).toFixed(0)}%`}</b> observed or user success</span></div><TaskDiagnostics data={diagnostics} />{data?.passAt && <div className="aw-reliability-row">{data.passAt.map((item: any) => <span key={item.k}>pass@{item.k}: <b>{item.passAt == null ? '—' : `${(item.passAt * 100).toFixed(0)}%`}</b> · pass^{item.k}: <b>{item.passPower == null ? '—' : `${(item.passPower * 100).toFixed(0)}%`}</b></span>)}</div>}<label className="aw-baseline-select">Baseline<select value={baselineIndex} onChange={event => void setBaseline(Number(event.target.value))}><option value={-1}>Choose confirmed Run…</option>{current.confirmedRuns.map((ref, index) => <option value={index} key={`${ref.source}:${ref.sessionId}:${ref.turnId}`}>{ref.sessionId.slice(0, 8)} · {ref.turnId}</option>)}</select></label><div className="aw-task-runs">{current.confirmedRuns.map(ref => <span key={`${ref.source}:${ref.sessionId}:${ref.turnId}`}>✓ {ref.sessionId.slice(0, 8)} · {ref.turnId}</span>)}</div>{current.suggestedRuns.length ? <div className="aw-task-suggestions"><b>Suggested runs</b>{current.suggestedRuns.map(ref => <button type="button" key={`${ref.source}:${ref.sessionId}:${ref.turnId}`} onClick={() => void confirm(ref)}>Confirm {ref.sessionId.slice(0, 8)} · {ref.turnId}</button>)}</div> : null}{error && <small>{error}</small>}<div className="aw-card-actions"><button type="button" className="aw-btn-view" onClick={load}>Refresh diagnostics</button><button type="button" className="aw-btn-view" onClick={suggest}>Suggest matching Runs</button></div></article>
}

function TaskDiagnostics({ data }: { data: any }) { if (!data?.entries?.length) return null; return <section className="aw-reliability-row"><b>Run trend</b>{data.entries.map((entry: any) => <div key={`${entry.ref.source}:${entry.ref.sessionId}:${entry.ref.turnId}`} style={{ display: 'grid', gridTemplateColumns: '1fr auto auto auto', gap: 8, paddingTop: 5, fontSize: 11 }}><span>{entry.model} · {entry.harness}</span><span>{Math.round(entry.metrics.durationMs / 1000)}s</span><span>{entry.metrics.retries} retries</span><span>{entry.metrics.failures} failures</span></div>)}{data.baseline && <><b style={{ display: 'block', marginTop: 8 }}>Regression history</b>{data.comparisons.map((comparison: any) => <div key={`${comparison.ref.source}:${comparison.ref.sessionId}:${comparison.ref.turnId}`} style={{ display: 'flex', justifyContent: 'space-between', paddingTop: 4, fontSize: 11 }}><span>{comparison.attribution.type === 'inconclusive' ? 'Inconclusive' : `Likely ${comparison.attribution.type} ${comparison.attribution.direction}`}</span><span>{comparison.trajectory.added} added · {comparison.trajectory.retries} retries · {comparison.trajectory.errors} errors</span></div>)}</>}</section> }
